// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AllBookmarks():Promise<Array<main.NoteDocument>>;

export function BookmarkById(arg1:string):Promise<main.NoteDocument>;
