// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllBookmarks() {
  return window['go']['main']['App']['AllBookmarks']();
}

export function BookmarkById(arg1) {
  return window['go']['main']['App']['BookmarkById'](arg1);
}
